version: "3.8"
services:
  broker:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=broker
  order-service:
    image: 91201210/order-service:latest
    ports:
      - "8080"
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  payment-service:
    image: 91201210/payment-service:latest
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  stock-service:
    image: 91201210/stock-service:latest
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker